### ISSUE TITLE
기존 소스 검토(@hamzzi)

### ISSUE THREAD

**Issue by swoohooh** [swoohooh/mmr#9]
- https://github.com/1lann/lol-replay
- https://github.com/EloGank/lol-replay-downloader

**Comment by hamzzi** [comment]
sample recording file
[KR_4300142522.zip](https://github.com/swoohooh/mmr/files/4475356/KR_4300142522.zip)

**Comment by hamzzi** [comment]
sample lol replay file: [KR-3494395523.zip](https://github.com/swoohooh/mmr/files/4475362/KR-3494395523.zip)

extract meta json: [meta.txt](https://github.com/swoohooh/mmr/files/4475366/meta.txt)
